iomesh/docs

docs/zbs-csi-driver/deployment.md

- update zbs-csi-driver deployment doc (relay iomesh/zbs-csi-driver#172)

docs: fix zbs-csi-driver ocp doc

---

README.md
docs/zbs-csi-driver/deployment.md
docs/zbs-csi-driver/overview.md
docs/zbs-operator/deployment.md
website/package-lock.json

Preview at http://192.168.24.87:3001/docs/next/zbs-csi-driver/overview

Refine all docs

---

docs/installation/prerequisites.md

Signed-off-by: Kai Zhang <kyle@smartx.com>

refine installation/prerequisites

---

website/package.json

Signed-off-by: Kai Zhang <kyle@smartx.com>

upgrade docusaurus to 1.14.7

---

docs/installation/install-and-setup-iomesh.md
docs/installation/prerequisites.md

preview: http://192.168.62.48:3000/docs/next/installation/prerequisites

feat(doc): refine install doc

---

website/core/Footer.js

Fix footer issues

---

website/siteConfig.js
website/static/index.html

1. url: "http://iomesh.com" -> "http://doc.iomesh.com"
2. baseUrl: "/docs/" -> "/"
3. homepage fix

fix(doc): change baseurl and website url

---

docs/additional-info/performance-testing.md
docs/deploy/install-iomesh.md
docs/deploy/prerequisites.md
docs/iomesh-operations/cluster-operations.md
docs/stateful-applications/iomesh-for-cassandra.md
docs/stateful-applications/iomesh-for-mongodb.md
docs/stateful-applications/iomesh-for-mysql.md

Accroding to https://www.markdownguide.org/basic-syntax/#adding-elements-in-lists, elements in lists should be indented.
fix #101
Signed-off-by: Kai Zhang <kyle@smartx.com>

docs: indent elements in lists

---

scripts/install_iomesh_coreos.sh
scripts/install_iomesh_el7.sh
scripts/install_iomesh_el8.sh

Wait until snapshot-controller is ready

---

docs/volume-operations/snapshot-restore-and-clone.md

revise some expressions of shapshot, restore, and clone

---

docs/about-iomesh/introduction.md
docs/additional-info/best-practice-in-production.md
docs/deploy/install-iomesh.md
docs/deploy/prerequisites.md
docs/deploy/setup-iomesh.md
docs/deploy/setup-snapshotclass.md
docs/deploy/setup-storageclass.md
docs/iomesh-operations/cluster-operations.md
docs/iomesh-operations/monitoring.md
docs/stateful-applications/iomesh-for-cassandra.md
docs/stateful-applications/iomesh-for-mongodb.md
docs/stateful-applications/iomesh-for-mysql.md
docs/volume-operations/create-volume.md
docs/volume-operations/expand-volume.md

修订其它 Markdown 文件，完善部分叙述语句，统一 yaml 文件显示风格。

revise other markdown files

---

docs/deploy/setup-storageclass.md

- Issue Link: https://github.com/iomesh/csi-driver/issues/182
- preview: http://192.168.62.48:3000/next/deploy/setup-storageclass

doc: add pv retain docs

---

docs/deploy/install-iomesh.md

update install iomesh on operatorhub

---

docs/references/metrics.md
website/sidebars.json

- preview: http://192.168.62.48:3001/next/references/metrics

feat(doc): add metrics doc

---

docs/assets/iomesh-operation/iomesh-prometheus-kubernetes-sd-example.yaml
docs/deploy/install-iomesh.md
docs/deploy/setup-iomesh.md
docs/deploy/setup-storageclass.md
docs/iomesh-operations/cluster-operations.md
docs/iomesh-operations/monitoring.md

将手动安装 IOMesh / 一键安装脚本 / 配置文件 中的 helm release name 保持一致

docs: correct helm install release name

---

docs/advanced-usage/external-iscsi.md
website/sidebars.json

请直接通过访问 http://192.168.25.87:3000/next/advanced-usage/external-iscsi 进行中文文档 review，review 结束后会交给 @zhongdeyu 进行翻译

docs: use IOMesh as iSCSI target

---

docs/deploy/install-iomesh.md
docs/deploy/prerequisites.md
docs/deploy/setup-iomesh.md

可对照 http://192.168.25.87:3001/next/deploy/prerequisites 进行中文文档 review，review 结束后会交给 @zhongdeyu 进行中英翻译

docs: all-flash mode

---

docs/deploy/install-iomesh.md

将 allFlash 字段调整为 diskDeploymentMode
review 地址 http://192.168.31.213:3000/next/deploy/install-iomesh#install-iomesh-cluster

docs: refine all-flash mode fields

---

docs/deploy/install-iomesh.md

请直接通过访问 http://192.168.31.213:3000/next/deploy/install-iomesh#install-iomesh 进行 review

docs: refine installation of iomesh

---

docs/deploy/install-iomesh.md

离线包下载链接中的内容是临时的，正式发布后会使用正确的下载链接
review 地址 http://192.168.25.87:3000/next/deploy/install-iomesh

docs: IOMesh offline installation

---

website/siteConfig.js
website/static/js/add-tracker.js

chore: add tracker script
